fos_user:
    db_driver: orm
    firewall_name: main
    user_class: FOS\UserBundle\Model\User
    from_email: {address: "fosub@localhost", sender_name: FOSUB}
    use_flash_notifications: false
    group:
        group_class:   FOS\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
